[[redirects]]
from = "/api/*"
to = "https://bai-valentines.onrender.com/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/"
status = 200

[build]
  command = "npm run build && echo \"INBOXLINK: $INBOXLINK\" && echo \"USERLINK: $USERLINK\""
